name: Kestra CI/CD
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Kestra validate
    steps:
      - name: Validate all flows on server-side
        uses: kestra-io/validate-action@develop
        with:
          directory: ./kestra/flows
          resource: flow
          server: https://0326-38-242-180-137.ngrok-free.app

  # If validation passed, deploy resources
  deploy:
    runs-on: ubuntu-latest
    name: Kestra deploy
    steps:
      - name: Deploy flows
        uses: kestra-io/deploy-action@develop
        with:
          namespace: company
          directory: ./kestra/flows
          server: https://0326-38-242-180-137.ngrok-free.app
