name: Kestra CI/CD
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Kestra validate
    steps:
      - name: Validate all flows on server-side
        uses: actions/kestra-validate-action@develop
        with:
          directory: ./kestra/flows
          server: https://335a-38-242-180-137.ngrok-free.app
          apiToken: ${{ secrets.KESTRA_API_TOKEN }}

  # If validation passed, deploy resources
  deploy:
    runs-on: ubuntu-latest
    name: Kestra deploy
    steps:
      - name: Deploy flows
        uses: actions/kestra-deploy-action@develop
        with:
          namespace: company.team
          directory: ./kestra/flows/company/team
          server: https://335a-38-242-180-137.ngrok-free.app
          apiToken: ${{ secrets.KESTRA_API_TOKEN }}

